using Entities.RealEstateInfoFiles;

public class CreateRealEstateInfoFileDTO
{
    public string Mantaghe { get; set; }
    public int TotalFloors { get; set; }
    public int UnitsPerFloor { get; set; }
    public decimal TotalPrice { get; set; }
    public decimal PricePerSquareMeter { get; set; }
    public int SquareMeters { get; set; }
    public int Floors { get; set; }
    public int BuiltArea { get; set; }
    public int Bedrooms { get; set; }
    public int Balconies { get; set; }
    public bool HasTelephone { get; set; }
    public KitchenType KitchenType { get; set; }
    public bool IsKitchenOpen { get; set; }
    public BathroomType BathroomType { get; set; }
    public FlooringType FlooringType { get; set; }
    public bool HasElevator { get; set; }
    public FacadeType FacadeType { get; set; }
    public DocumentType DocumentType { get; set; }
    public bool HasParking { get; set; }
    public bool HasStorage { get; set; }
    public string BuildingAge { get; set; }
    public bool IsFurnished { get; set; }
    public bool HasGas { get; set; }
    public bool HasVideoIntercom { get; set; }
    public bool HasCooler { get; set; }
    public bool HasRemoteControlDoor { get; set; }
    public bool HasRadiator { get; set; }
    public bool HasPackageHeater { get; set; }
    public bool IsRenovated { get; set; }
    public bool HasJacuzzi { get; set; }
    public bool HasSauna { get; set; }
    public bool HasPool { get; set; }
    public bool HasLobby { get; set; }
    public bool HasDuctSplit { get; set; }
    public bool HasChiller { get; set; }
    public bool HasRoofGarden { get; set; }
    public bool HasMasterRoom { get; set; }
    public bool HasNoElevator { get; set; }
    public bool HasSplitAC { get; set; }
    public bool HasJanitorService { get; set; }
    public bool HasMeetingHall { get; set; }
    public bool HasFanCoil { get; set; }
    public bool HasGym { get; set; }
    public bool HasCCTV { get; set; }
    public bool HasEmergencyPower { get; set; }
    public bool IsFlat { get; set; }
    public bool HasUnderfloorHeating { get; set; }
    public bool HasFireAlarm { get; set; }
    public bool HasFireExtinguishingSystem { get; set; }
    public bool HasCentralVacuum { get; set; }
    public bool HasSecurityDoor { get; set; }
    public bool HasLaundry { get; set; }
    public bool IsSoldWithTenant { get; set; }
    public bool HasCentralAntenna { get; set; }
    public bool HasBackyard { get; set; }
    public bool HasServantService { get; set; }
    public bool HasBarbecue { get; set; }
    public bool HasElectricalPanel { get; set; }
    public bool HasConferenceHall { get; set; }
    public bool HasGuardService { get; set; }
    public bool HasAirHandler { get; set; }
    public bool HasCentralSatellite { get; set; }
    public bool HasGarbageChute { get; set; }
    public bool HasLobbyManService { get; set; }
    public bool HasGuardOrJanitorService { get; set; }
}