services:
  kolbeh.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=kolbehdb,1433;Database=KolbehDb;User Id=sa;Password=StrongPass123!;Encrypt=False;TrustServerCertificate=True;Connect Timeout=30;Command Timeout=30
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - default

  kolbehdb:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPass123!
      - MSSQL_PID=Express
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - default