services:
  kolbeh.api:
    image: ${DOCKER_REGISTRY-}kolbehapi
    build:
      context: .
      dockerfile: MyApi/Dockerfile
    depends_on:
      - kolbehdb
    networks:
      - kolbeh-network
    restart: on-failure

  kolbehdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: kolbehdb
    networks:
      - kolbeh-network

volumes:
  sqlserver_data:

networks:
  kolbeh-network:
    driver: bridge